In [1]:
#Data Loading and Initital Inspection
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/batting_stats.csv")
df.head() #gets the first 5 rows

,Rk,Player,Age,Team,Lg,WAR,G,PA,AB,R,...,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,HBP
0,357,A.J. Ellis,35,2TM,NL,-0.1,64,196,171,11,...,2,1,19,31,0.216,0.301,0.298,0.599,63,2
1,416,AJ Pollock,35,2TM,2LG,-0.7,54,144,133,15,...,0,1,9,32,0.165,0.215,0.308,0.524,47,0
2,284,Aaron Hicks#,33,2TM,AL,0.5,93,312,269,44,...,6,0,42,69,0.253,0.353,0.383,0.735,106,0
3,193,Aaron Hill,34,2TM,2LG,1.5,125,429,378,48,...,4,2,41,59,0.262,0.336,0.378,0.714,89,3
4,301,Abraham Almonte#,26,2TM,2LG,0.8,82,258,232,36,...,7,1,21,52,0.250,0.310,0.409,0.719,93,0

In [3]:
df.shape  #gets the rows and columns

(4502, 25)

In [4]:
df.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Lg', 'WAR', 'G', 'PA', 'AB', 'R', 'H',
       '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG',
       'OPS', 'OPS+', 'HBP'],
      dtype='str')

In [5]:
df.info() #gets the data types of each column

<class 'pandas.DataFrame'>
RangeIndex: 4502 entries, 0 to 4501
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      4502 non-null   int64
 1   Player  4502 non-null   str
 2   Age     4502 non-null   int64
 3   Team    4502 non-null   str
 4   Lg      4502 non-null   str
 5   WAR     4502 non-null   float64
 6   G       4502 non-null   int64
 7   PA      4502 non-null   int64
 8   AB      4502 non-null   int64
 9   R       4502 non-null   int64
 10  H       4502 non-null   int64
 11  2B      4502 non-null   int64
 12  3B      4502 non-null   int64
 13  HR      4502 non-null   int64
 14  RBI     4502 non-null   int64
 15  SB      4502 non-null   int64
 16  CS      4502 non-null   int64
 17  BB      4502 non-null   int64
 18  SO      4502 non-null   int64
 19  BA      4502 non-null   float64
 20  OBP     4502 non-null   float64
 21  SLG     4502 non-null   float64
 22  OPS     4502 non-null   float64
 23  OPS+    4502 non-null   int64
 24  HBP     4502 non-null   int64
dtypes: float64(5), int64(17), str(3)
memory usage: 879.4 KB

In [6]:
df.describe() #summary of stats

,Rk,Age,WAR,G,PA,AB,R,H,2B,3B,...,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,HBP
count,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,...,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000,4502.000000
mean,214.847845,28.219680,1.299889,99.860729,368.357619,329.782319,44.625056,83.744114,16.696357,1.569080,...,5.481120,1.852066,31.234562,79.277432,0.246691,0.315709,0.407390,0.723101,96.015549,3.897601
std,125.450072,3.753566,1.846271,38.567880,177.524022,158.152767,26.357358,45.911169,10.093827,1.898445,...,7.735029,2.290183,20.911448,39.619515,0.036120,0.039879,0.078585,0.109505,28.213098,3.834553
min,1.000000,19.000000,-3.300000,24.000000,102.000000,100.000000,3.000000,13.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,7.000000,0.104000,0.154000,0.167000,0.322000,-11.000000,0.000000
25%,107.250000,25.000000,0.000000,64.000000,210.000000,188.000000,23.000000,44.000000,8.000000,0.000000,...,1.000000,0.000000,16.000000,47.000000,0.224000,0.290000,0.356000,0.649250,78.000000,1.000000
50%,212.000000,28.000000,0.900000,101.000000,345.000000,310.500000,39.000000,76.000000,15.000000,1.000000,...,3.000000,1.000000,26.000000,72.000000,0.249000,0.315000,0.406000,0.722000,96.000000,3.000000
75%,321.000000,31.000000,2.200000,135.000000,521.750000,467.000000,62.000000,119.000000,24.000000,2.000000,...,7.000000,3.000000,42.000000,106.000000,0.271000,0.341000,0.457000,0.791000,114.000000,5.000000
max,465.000000,43.000000,10.800000,162.000000,753.000000,681.000000,149.000000,217.000000,59.000000,15.000000,...,73.000000,20.000000,145.000000,219.000000,0.373000,0.490000,0.741000,1.185000,223.000000,34.000000

In [7]:
#demonstrating basic python data structures
hr = pd.Series([10, 20, 30], index=['player a','player b','player c'])
hr

player a    10
player b    20
player c    30
dtype: int64

In [8]:
data = {
'name': ['John', 'Bob', 'Tim'],
'HR': [12, 25, 40],
'BB': [18, 55, 90]
}
sample_df = pd.DataFrame(data)
sample_df

   name  HR  BB
0  John  12  18
1   Bob  25  55
2   Tim  40  90

In [9]:
#indexing
df.iloc[0:5]

,Rk,Player,Age,Team,Lg,WAR,G,PA,AB,R,...,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,HBP
0,357,A.J. Ellis,35,2TM,NL,-0.1,64,196,171,11,...,2,1,19,31,0.216,0.301,0.298,0.599,63,2
1,416,AJ Pollock,35,2TM,2LG,-0.7,54,144,133,15,...,0,1,9,32,0.165,0.215,0.308,0.524,47,0
2,284,Aaron Hicks#,33,2TM,AL,0.5,93,312,269,44,...,6,0,42,69,0.253,0.353,0.383,0.735,106,0
3,193,Aaron Hill,34,2TM,2LG,1.5,125,429,378,48,...,4,2,41,59,0.262,0.336,0.378,0.714,89,3
4,301,Abraham Almonte#,26,2TM,2LG,0.8,82,258,232,36,...,7,1,21,52,0.250,0.310,0.409,0.719,93,0

In [10]:
df.loc[:, ["Player", "Team", "AB", "BA"]]

                    Player Team   AB     BA
0               A.J. Ellis  2TM  171  0.216
1               AJ Pollock  2TM  133  0.165
2             Aaron Hicks#  2TM  269  0.253
3               Aaron Hill  2TM  378  0.262
4         Abraham Almonte#  2TM  232  0.250
...                    ...  ...  ...    ...
4497  Yadiel HernÃƒÂ¡ndez*  WSN  305  0.269
4498             Yan Gomes  WSN  109  0.284
4499             Yan Gomes  WSN  314  0.223
4500             Yan Gomes  WSN  218  0.271
4501         Yunel Escobar  WSN  535  0.314

[4502 rows x 4 columns]

In [17]:
#boolean filtering
df[df["BA"] > .350]

,Rk,Player,Age,Team,Lg,WAR,G,PA,AB,R,...,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,HBP
772,202,Jose Iglesias,30,BAL,AL,1.3,39,150,142,16,...,0,0,3,17,0.373,0.400,0.556,0.956,157,4
2433,60,Luis ArrÃƒÂ¡ez*,26,MIA,NL,4.6,147,617,574,71,...,3,2,35,34,0.354,0.393,0.469,0.861,128,4
2941,93,DJ LeMahieu,31,NYY,AL,3.0,50,216,195,41,...,3,0,18,21,0.364,0.421,0.590,1.011,178,2
4435,128,Juan Soto*,21,WSN,NL,2.3,47,196,154,39,...,6,2,41,28,0.351,0.490,0.695,1.185,217,1